dbStuff/dbStuff/urls.py
from django.contrib import admin
from django.urls import path, include

# for image files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Event App
    path('', include('events.urls')),

    # Members App
    path('members/', include('django.contrib.auth.urls')),  # for authentication
    path('members/', include('members.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# CUSTOMIZE THE ADMIN SECTION
# Configure Amin Titles
admin.site.site_header = "My Events Admin"
admin.site.site_title = "DB Stuff"
admin.site.index = "Admin Page"

dbStuff/events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),

    # CREATE TEXT FILE
    path('venue_text', views.venue_text, name='venue-text'),
    # CREATE CSV FILE
    path('venue_csv', views.venue_csv, name='venue-csv'),
    # CREATE PDF FILE
    path('venue_pdf', views.venue_pdf, name='venue-pdf'),

    # CREATE SEARCH VENUE
    path('search', views.search_venues, name='search-venue'),

    # CREATE SEARCH EVENT
    path('search_events', views.search_events, name='search-events'),

    # ADMIN DASHBOARD
    path('admin_dashboard', views.admin_dashboard, name='admin-dashboard'),

    # VENUE AND EVENTS
    # path('venue_event/<venue_id>', views.venue_event, name='venue-event'),

    # EVENT PATHs
    path('addevents/', views.add_events, name='add-events'),
    path('events/', views.all_events, name='list-events'),
    path('update_event/<event_id>', views.update_event, name='update-event'),
    path('delete_event/<event_id>', views.delete_event, name='delete-event'),

    # VENUE PATHs
    path('addvenue/', views.add_venue, name='add-venue'),
    path('list_venues/', views.list_venue, name='list-venue'),
    path('show_venue/<venue_id>', views.show_venues, name='show-venue'),
    path('update_venue/<venue_id>', views.update_venue, name='update-venue'),
    path('delete_venue/<venue_id>', views.delete_venue, name='delete-venue'),

    # MY EVENTS
    path('my_events', views.my_events, name='my-events'),


]

dbStuff/members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login_user/', views.loginPage, name='login-Page'),
    path('logout_user/', views.logOutPage, name='logout-Page'),
    path('register_user/', views.registerUser, name='register-user'),


]

dbStuff/events/forms.py
from django import forms
# ModelForm needed cos we will add data to the models, helps add data into the DB
from django.forms import ModelForm
from .models import Venue, Event  # The TABLE to pull data from


# Create a venue form
class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = ('venue_name', 'veune_address', 'veune_address', 'veune_web',
                  'veune_zip_code', 'veune_phone', 'veune_email_address', 'venue_image',)
        # "__all__"
        labels = {
            'venue_name': '',
            'veune_address': '',
            'veune_web': '',
            'veune_zip_code': '',
            'veune_phone': '',
            'veune_email_address': '',
            'venue_image': '',
        }
        widgets = {
            'venue_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Venue Name'}),
            'veune_address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'veune_web': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Website'}),
            'veune_zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'veune_phone': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '0243...'}),
            'veune_email_address': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email address'}),

        }

# CREATE ADMIN SuperUser ADD_EVENT FORMS CLASS


class EventFormAdmin(ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'event_date', 'event_venue',
                  'event_organizer', 'attendees', 'event_description',)
        labels = {
            'event_name': '',
            'event_date': '',
            'event_venue': 'Venue',
            'event_organizer': 'Organizer',
            'attendees': 'Attendees',
            'event_description': '',
        }
        widgets = {
            'event_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD HH:MM:SS'}),
            'event_venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'event_organizer': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Organizer'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'event_description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


# USERS ADD_EVENT FORM
class EventFormUsers(ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'event_date', 'event_venue',
                  'attendees', 'event_description')
        labels = {
            'event_name': '',
            'event_date': '',
            'event_venue': 'Venue',
            'attendees': 'Attendees',
            'event_description': '',
        }
        widgets = {
            'event_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD HH:MM:SS'}),
            'event_venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'event_description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }

dbStuff/events/views.py
from django.shortcuts import render
# working with calender
import calendar
from calendar import HTMLCalendar
from datetime import datetime
# to redicrect to different page
from django.http import HttpResponseRedirect
# Import all DBs tables
from .models import Event, Venue
# Import USER model
from django.contrib.auth.models import User
# Import forms from "forms.py"
from .forms import VenueForm, EventFormUsers, EventFormAdmin
# to diplay message on pages
from django.contrib import messages
# to help generate text file
from django.http import HttpResponse
# to help generate csv files
import csv
# FOR PDF IMPORT ALL
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# Import Pagination Stuff
from django.core.paginator import Paginator


# Create your views here.

# hompage and calender
def index(request, year=datetime.now().year, month=datetime.now().strftime('%B')):
    name = "Monyo"

    month = month.capitalize()  # convert case to initial case letters

    # Convert month name to number
    month_number = list(calendar.month_name).index(month)
    month_number = int(month_number)

    # create a calendar
    cal = HTMLCalendar().formatmonth(
        year,
        month_number
    )

    # Get current year and date
    timeNow = datetime.now()
    current_year = timeNow.year

    # Query the Event Modal for Dates
    EventInMonth = Event.objects.filter(
        event_date__year=year,
        # Assign the month number, you can enter the month number (1,2,3,4,...12)
        event_date__month=month_number,
    )

    # Get current time

    # READ datetime @ gooogle, python datetime
    time = timeNow.strftime('%D %I:%M:%S %A')

    return render(request, 'index.html', {
        "last_name": name,
        "year": year,
        "month": month,
        "mon_number": month_number,
        "calender": cal,
        "currentYear": current_year,
        "currentTime": time,
        "AllEventInMonth": EventInMonth,
    })

# ADMIN DASHBOARD


def admin_dashboard(request):
    # fetch all venue
    vennueWithEvent = Venue.objects.all()

    # count the total in database
    event_count = Event.objects.all().count()
    venue_count = Venue.objects.all().count()
    user_connt = User.objects.all().count()

    # update approvals in Database
    allEventToApprove = Event.objects.all().order_by('-event_date')
    if request.user.is_superuser:
        if request.method == "POST":
            id_list = request.POST.getlist('approvedCheckboxes')

            # uncheck all events
            allEventToApprove.update(approveEvent=False)

            # update the database
            for x in id_list:
                Event.objects.filter(pk=int(x)).update(
                    approveEvent=True)  # convert the pk to integer first

            messages.success(request, ("Events approval has been updated"))
            return HttpResponseRedirect('/events')
        else:
            return render(request, 'event/admin_approval.html', {
                'allEventToApprove': allEventToApprove,
                'totalEvents': event_count,
                'totalVenue': venue_count,
                'totalUsers': user_connt,
                'vennueWithEvent': vennueWithEvent,
            })
    else:
        messages.success(
            request, ("You are not authorized to view this page..."))
        return HttpResponseRedirect('/')

# Venue and Event page


def venue_event(request, venue_id):
    # Grab the venue
    venueWanted = Venue.objects.get(id=venue_id)
    # Grab the events for the venueWanted
    showEvents = venueWanted.event_set.all()

    if showEvents:
        return render(request, 'event/venue_and_event.html', {
            'showEvents': showEvents,
        })
    else:
        messages.success(request, ("No Events available..."))
        return HttpResponseRedirect('event/admin_dashboard')


# MY EVENTS
def my_events(request):
    if request.user.is_authenticated:
        me = request.user.id
        events = Event.objects.filter(attendees=me).order_by('event_date')
        return render(request, 'event/my_events.html', {
            'my_eventsEvents': events,
        })
    else:
        messages.success(request, ("You are not authorized view this page..."))
        return HttpResponseRedirect('/')
# GENERATE A TEXT FILE


def venue_text(request):
    textResonse = HttpResponse(content_type='text/plain')
    textResonse['Content-Disposition'] = 'attachment; filename=venues.txt'

    # Designate The Venue Model
    venueTextOutput = Venue.objects.all()

    # Create blank list
    lines = []
    # Loop Through and Output
    for venue in venueTextOutput:
        # adding DB columns to the text file
        lines.append(
            f'{venue.venue_name}\n{venue.veune_address}\n{venue.veune_zip_code}\n{venue.veune_phone}\n{venue.veune_web}\n{venue.veune_email_address}\n\n\n\n')

    # lines = ["This is line 1\n",
    #          "This is line 2\n",
    #          "This is line 3\n",
    #          "This is line 4\n\n",

    #          "Jonas is Awesome\n\n",
    #          ]

    # Write to TextFile
    textResonse.writelines(lines)
    return textResonse

# GENERATE A CSV / EXCEL FILE


def venue_csv(request):
    textResonse = HttpResponse(content_type='text/csv')
    textResonse['Content-Disposition'] = 'attachment; filename=venues.csv'

    # Creating a csv writer
    csvWriter = csv.writer(textResonse)

    # Designate The Venue Model
    venueTextOutput = Venue.objects.all()

    # add columns to csv file
    csvWriter.writerow(['Venue Name', 'Address', 'Zip Code',
                       'Phone Numbers', 'Website', 'Email'])

    # Loop Through and Output
    for venue in venueTextOutput:
        # adding DB columns to the csv filegit
        csvWriter.writerow(
            [venue.venue_name, venue.veune_address, venue.veune_zip_code, venue.veune_phone, venue.veune_web, venue.veune_email_address])

    return textResonse

# GENERATE A TEXT FILE
# befor you begin, install reportLab in the terminal (pip install)


def venue_pdf(request):
    # Create Bytestream buffer
    buf = io.BytesIO()
    # Create a canvas
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # Create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont('Helvetica', 14)

    #  Add some lines of text
    # lines = [
    #     "This is line 1",
    #     "This is line 2",
    #     "This is line 3",
    #     "This is line 4",
    # ]

    # Designate the VENUE Model
    venueToPdf = Venue.objects.all()

    # Create blank list
    line = []

    for venue in venueToPdf:
        line.append(venue.venue_name)
        line.append(venue.veune_address)
        line.append(venue.veune_zip_code)
        line.append(venue.veune_phone)
        line.append(venue.veune_web)
        line.append(venue.veune_email_address)
        line.append("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

    # Loop
    for line in line:
        textob.textLine(line)

    # Finish up
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    # Return something
    return FileResponse(buf, as_attachment=True, filename='venue.pdf')

# ADD SEARCH VENUE BUTTON ON PAGE


def search_venues(request):
    if request.method == "POST":
        # receiving word from the search input
        searchedWord = request.POST['searched']
        # make search by venue_name in the model
        SearchVenue = Venue.objects.filter(venue_name__contains=searchedWord)

        return render(request, 'venue/search_venues.html', {
            'searchedWord': searchedWord,
            'SearchVenue': SearchVenue
        })
    else:
        return render(request, 'venue/search_venues.html', {})

# ADD SEARCH EVENTS ON PAGE


def search_events(request):
    if request.method == "POST":
        # receiving word from the search input
        searchedWord = request.POST['searched']
        # make search by venue_name in the model
        SearchEvent = Event.objects.filter(event_name__contains=searchedWord)

        return render(request, 'event/search_events.html', {
            'searchedWord': searchedWord,
            'SearchEvent': SearchEvent
        })
    else:
        return render(request, 'event/search_events.html', {})


# EVENTS SECTION VIEW
# Selecting from the Event TABLE IN DATABASE

# ADDING EVENTS INTO THE DB
def add_events(request):
    submitted = False
    if request.method == "POST":
        # if request.user.id == 4:
        if request.user.is_superuser:
            addEventForm = EventFormAdmin(request.POST)

            # form validation
            if addEventForm.is_valid():
                addEventForm.save()
                return HttpResponseRedirect('/addevents')
        else:
            addEventForm = EventFormUsers(request.POST)

            # form validation
            if addEventForm.is_valid():
                # addEventForm.save()

                event = addEventForm.save(commit=False)
                event.event_organizer = request.user  # linking to logged-in-user "request.user"
                event.save()
                return HttpResponseRedirect('/addevents')
    else:
        # just load the page when visited
        if request.user.is_superuser:
            addEventForm = EventFormAdmin
        else:
            addEventForm = EventFormUsers

        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'event/add_events.html', {
        'submitted': submitted,
        'addEventForm': addEventForm,
    })

# LISTING ALL EVENTS


def all_events(request):

    # selecting all columns from the Event tables
    # use '?' in .order_by to make list random when page loads
    events_list = Event.objects.all().order_by('event_date')

    return render(request, 'event/event_lists.html', {
        'eventsList': events_list
    })

# UPDATE / EDIT EVENTS

dbStuff/events/templates/venue/add_venue.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <center>
            <h1>Add Venue</h1>
            <hr>
            <br>
            USER ID: {{ user.id }}
            <br><br>
        </center> 

        {% if submitted %}
            Your Venue Was Submitted Successfully!!!
            {{ python_diamond_pattern  }}
            
        {% else %}
            <!-- Add forms -->

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- add form to page -->
                {{ addVenueForm.as_p }}

                <div align="right">
                    <input class="btn btn-outline-success" type="submit" value="Submit"/>
                </div>

            </form>
        {% endif %}   
    {% else%}
        <div class="alert alert-danger d-flex alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <strong>
                <p>Sorry You have to Log in first...</p>                
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <a href="{% url 'members:login-Page' %}">Login Here</a>
    {% endif%}
    


{% endblock %}

dbStuff/events/templates/venue/search_venues.html
{% extends 'base.html' %}

{% block content %}

    <!-- searched output -->
    {% if searchedWord %}
        <h1>You searched for {{ searchedWord }}</h1> 
        <br>

        <!-- searched record output -->
        {% for SearchVenue in SearchVenue %}
            <div class="card">
                <div class="card-header">
                    <strong class="text-uppercase">{{ SearchVenue }}</strong>
                </div>
    
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <p class="card-text">
                        <ul>
                            {% if SearchVenue.veune_address %}
                                <li>Address: {{ SearchVenue.veune_address }} </li>
                            {% endif %}

                            {% if SearchVenue.veune_zip_code %}
                                <li>Zip Code: {{ SearchVenue.veune_zip_code }} </li>
                            {% endif %}

                            {% if SearchVenue.veune_phone %}
                                <li>Phone: {{ SearchVenue.veune_phone }} </li>
                            {% endif %}

                            {% if SearchVenue.veune_web %}
                                <li>Website: <a href="#">{{ SearchVenue.veune_web }}</a> </li>
                            {% endif %}

                            {% if SearchVenue.veune_email_address %}
                            <li><b>Email:</b> <br>
                                {{ SearchVenue.veune_email_address }}
                            </li>
                            {% endif %}
                            
                            {% if SearchVenue.owner %}
                                <li>Created By: {{ SearchVenue.owner }} </li>
                            {% endif %}
                        </ul>
                    </p> 
                </div>
            </div> 
            <br>
        {% endfor %}  

    {% else %}
        <h1>Hey! You forgot to Enter a word to search for a Venue...</h1>
    {% endif %}

{% endblock %}

dbStuff/events/templates/venue/show_venue.html
{% extends 'base.html' %}

{% block content %}

         <br>
        <br>
         <br>
         </a> <br>
         <br>


        <div class="card">
            <div class="card-header">
                <strong class="text-uppercase">Venue</strong>
            </div>

            <div class="card-body">
                <h5 class="card-title">{{ ShowVenue }}</h5>
                <p class="card-text">
                    <ul>
                        <li>Address: {{ ShowVenue.veune_address }} </li>
                        <li>Zip Code: {{ ShowVenue.veune_zip_code }} </li>
                        <li>Phone: {{ ShowVenue.veune_phone }} </li>
                        <li>Website: <a href="#">{{ ShowVenue.veune_web }}</a> </li>
                        <li><b>Email:</b> <br>
                            {{ ShowVenue.veune_email_address }}
                        </li>
                        <li>Created By: {{ venue_owner }} </li>
                    </ul>
                </p> 
                <br>
                {% if ShowVenue.venue_image %}
                    <img src="{{ ShowVenue.venue_image.url }}" width="200"/>
                {% endif %}
            </div>
        </div>  
    
    


{% endblock %}

dbStuff/events/templates/venue/update_venue.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Edit Venue...</h1>
        <br>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token%}
            
            <!-- display forms -->
            {{ VenueFormToUpdate.as_p }}

            <!-- update button -->
            <div align="right">
                <input type="submit" value="Update" class="btn btn-success">
            </div>

        </form>

    {% else %}
        <div class="alert alert-danger d-flex alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <strong>
                <p>Sorry You have to Log in first...</p>                
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <a href="{% url 'members:login-Page' %}">Login Here</a>
    {% endif %}
{% endblock %}

dbStuff/events/templates/venue/venue_and_event.html
{% extends 'base.html' %}

{% block content %}
    
    <center>
        <h1>Venue and Events</h1>
        <br>
    </center>

    













{% endblock %}

dbStuff/events/templates/venue/venue_lists.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>All Venues...</h1>
    <br>
    
    <table class="table table-hover table-striped table-bordered">

        
        {% for venue in venuePagination %}
            <tr>
                <td>
                    {{ venue }} - {{ venue.veune_web }} 
                </td>
                
                <!-- adding buttons -->
                <td align="center">
                    <a href="{% url 'events:show-venue' venue.id %}" class="btn btn-outline-secondary btn-sm">View</a>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'events:update-venue' venue.id %}" class="btn btn-outline-success btn-sm">Edit</a>
                        <a href="{% url 'events:delete-venue' venue.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}  
    
    </table>
    <br>
    <br>

    <!-- Insert Pagination [1, 2, 3] -->
    {{ venuePagination }} <br>
    Has Previous: {{ venuePagination.has_previous }} <br>
    Has Next: {{ venuePagination.has_next }} <br>
    Current Page: {{ venuePagination.number }} <br>
    Number of Pages: {{ venuePagination.paginator.num_pages }} <br>
    Number of Next pages: {{ venuePagination.next_page_numbe }} <br>
    Number of Previous Pages: {{ venuePagination.previous_page_numbe }}"<br><br>

    <hr><br><br>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center"> 
            <!-- Setting the left side of the pagination -->
            {% if venuePagination.has_previous %}
                </li><li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ venuePagination.previous_page_number }}">Previous</a></li>
            {% endif%}

            <!-- Setting the MIDDLE side of the pagination -->
            <!-- <li class="page-item disabled"><a class="page-link" href="#">Page {{ venuePagination.number }} of {{ venuePagination.paginator.num_pages }} </a> </li> -->

            <!-- Show individual page numbers -->
            {% for i in showNums %}
                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endfor %}
            
            <!-- Setting the RIGHT side of the pagination -->
            {% if venuePagination.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ venuePagination.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ venuePagination.paginator.num_pages }}">Last &raquo</a> </li>
            {% endif%}
        </ul>
    </nav>

{% endblock %}