templateAndCustomHTML/template1/urls.py
from django.urls import path
from . import views

app_name = "templat1"
urlpatterns = [
    path('', views.index, name="index"),
]

templateAndCustomHTML/templateAndCustomHTML/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('template1.urls')),
]

templateAndCustomHTML/template1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'templat1/index.html', {})

templateAndCustomHTML/template1/templates/templat1/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    
    {% include 'templat1/navbar.html' %}
 
    <br><br>
  
        {% block content%}

            <!-- content goes here -->

        {% endblock %}

    <br><br>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

templateAndCustomHTML/template1/templates/templat1/index.html
{% extends 'templat1/base.html' %}

{% block content %}

    <center>
        <h1>Hello, world!</h1>
        <br>
        <h1>Template Custom Page sucessful</h1>
        <h3>Page is using <b style="color: red;"> BLOCK CONTENT</b> from <b style="color: red;">BASE.HTML</b> (layout)</h3>
    </center>

{% endblock %}

templateAndCustomHTML/template1/templates/templat1/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'templat1:index' %}">Template Test</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                    </a>
                    <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>

            </ul>

            <form class="d-flex" role="search">

                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>

            </form>

        </div>
    </div>
</nav>