dbStuff/dbStuff/urls.py
from django.contrib import admin
from django.urls import path, include

# for image files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Event App
    path('', include('events.urls')),

    # Members App
    path('members/', include('django.contrib.auth.urls')),  # for authentication
    path('members/', include('members.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# CUSTOMIZE THE ADMIN SECTION
# Configure Amin Titles
admin.site.site_header = "My Events Admin"
admin.site.site_title = "DB Stuff"
admin.site.index = "Admin Page"

dbStuff/events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),

    # CREATE TEXT FILE
    path('venue_text', views.venue_text, name='venue-text'),
    # CREATE CSV FILE
    path('venue_csv', views.venue_csv, name='venue-csv'),
    # CREATE PDF FILE
    path('venue_pdf', views.venue_pdf, name='venue-pdf'),

    # CREATE SEARCH VENUE
    path('search', views.search_venues, name='search-venue'),

    # CREATE SEARCH EVENT
    path('search_events', views.search_events, name='search-events'),

    # ADMIN DASHBOARD
    path('admin_dashboard', views.admin_dashboard, name='admin-dashboard'),

    # VENUE AND EVENTS
    # path('venue_event/<venue_id>', views.venue_event, name='venue-event'),

    # EVENT PATHs
    path('addevents/', views.add_events, name='add-events'),
    path('events/', views.all_events, name='list-events'),
    path('update_event/<event_id>', views.update_event, name='update-event'),
    path('delete_event/<event_id>', views.delete_event, name='delete-event'),

    # VENUE PATHs
    path('addvenue/', views.add_venue, name='add-venue'),
    path('list_venues/', views.list_venue, name='list-venue'),
    path('show_venue/<venue_id>', views.show_venues, name='show-venue'),
    path('update_venue/<venue_id>', views.update_venue, name='update-venue'),
    path('delete_venue/<venue_id>', views.delete_venue, name='delete-venue'),

    # MY EVENTS
    path('my_events', views.my_events, name='my-events'),


]

dbStuff/members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login_user/', views.loginPage, name='login-Page'),
    path('logout_user/', views.logOutPage, name='logout-Page'),
    path('register_user/', views.registerUser, name='register-user'),


]

dbStuff/events/forms.py
from django import forms
# ModelForm needed cos we will add data to the models, helps add data into the DB
from django.forms import ModelForm
from .models import Venue, Event  # The TABLE to pull data from


# Create a venue form
class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = ('venue_name', 'veune_address', 'veune_address', 'veune_web',
                  'veune_zip_code', 'veune_phone', 'veune_email_address', 'venue_image',)
        # "__all__"
        labels = {
            'venue_name': '',
            'veune_address': '',
            'veune_web': '',
            'veune_zip_code': '',
            'veune_phone': '',
            'veune_email_address': '',
            'venue_image': '',
        }
        widgets = {
            'venue_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Venue Name'}),
            'veune_address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'veune_web': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Website'}),
            'veune_zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'veune_phone': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '0243...'}),
            'veune_email_address': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email address'}),

        }

# CREATE ADMIN SuperUser ADD_EVENT FORMS CLASS


class EventFormAdmin(ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'event_date', 'event_venue',
                  'event_organizer', 'attendees', 'event_description',)
        labels = {
            'event_name': '',
            'event_date': '',
            'event_venue': 'Venue',
            'event_organizer': 'Organizer',
            'attendees': 'Attendees',
            'event_description': '',
        }
        widgets = {
            'event_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD HH:MM:SS'}),
            'event_venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'event_organizer': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Organizer'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'event_description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


# USERS ADD_EVENT FORM
class EventFormUsers(ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'event_date', 'event_venue',
                  'attendees', 'event_description')
        labels = {
            'event_name': '',
            'event_date': '',
            'event_venue': 'Venue',
            'attendees': 'Attendees',
            'event_description': '',
        }
        widgets = {
            'event_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD HH:MM:SS'}),
            'event_venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'event_description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }

dbStuff/events/views.py
from django.shortcuts import render
# working with calender
import calendar
from calendar import HTMLCalendar
from datetime import datetime
# to redicrect to different page
from django.http import HttpResponseRedirect
# Import all DBs tables
from .models import Event, Venue
# Import USER model
from django.contrib.auth.models import User
# Import forms from "forms.py"
from .forms import VenueForm, EventFormUsers, EventFormAdmin
# to diplay message on pages
from django.contrib import messages
# to help generate text file
from django.http import HttpResponse
# to help generate csv files
import csv
# FOR PDF IMPORT ALL
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# Import Pagination Stuff
from django.core.paginator import Paginator


# Create your views here.

# hompage and calender
def index(request, year=datetime.now().year, month=datetime.now().strftime('%B')):
    name = "Monyo"

    month = month.capitalize()  # convert case to initial case letters

    # Convert month name to number
    month_number = list(calendar.month_name).index(month)
    month_number = int(month_number)

    # create a calendar
    cal = HTMLCalendar().formatmonth(
        year,
        month_number
    )

    # Get current year and date
    timeNow = datetime.now()
    current_year = timeNow.year

    # Query the Event Modal for Dates
    EventInMonth = Event.objects.filter(
        event_date__year=year,
        # Assign the month number, you can enter the month number (1,2,3,4,...12)
        event_date__month=month_number,
    )

    # Get current time

    # READ datetime @ gooogle, python datetime
    time = timeNow.strftime('%D %I:%M:%S %A')

    return render(request, 'index.html', {
        "last_name": name,
        "year": year,
        "month": month,
        "mon_number": month_number,
        "calender": cal,
        "currentYear": current_year,
        "currentTime": time,
        "AllEventInMonth": EventInMonth,
    })

# ADMIN DASHBOARD


def admin_dashboard(request):
    # fetch all venue
    vennueWithEvent = Venue.objects.all()

    # count the total in database
    event_count = Event.objects.all().count()
    venue_count = Venue.objects.all().count()
    user_connt = User.objects.all().count()

    # update approvals in Database
    allEventToApprove = Event.objects.all().order_by('-event_date')
    if request.user.is_superuser:
        if request.method == "POST":
            id_list = request.POST.getlist('approvedCheckboxes')

            # uncheck all events
            allEventToApprove.update(approveEvent=False)

            # update the database
            for x in id_list:
                Event.objects.filter(pk=int(x)).update(
                    approveEvent=True)  # convert the pk to integer first

            messages.success(request, ("Events approval has been updated"))
            return HttpResponseRedirect('/events')
        else:
            return render(request, 'event/admin_approval.html', {
                'allEventToApprove': allEventToApprove,
                'totalEvents': event_count,
                'totalVenue': venue_count,
                'totalUsers': user_connt,
                'vennueWithEvent': vennueWithEvent,
            })
    else:
        messages.success(
            request, ("You are not authorized to view this page..."))
        return HttpResponseRedirect('/')

# Venue and Event page


def venue_event(request, venue_id):
    # Grab the venue
    venueWanted = Venue.objects.get(id=venue_id)
    # Grab the events for the venueWanted
    showEvents = venueWanted.event_set.all()

    if showEvents:
        return render(request, 'event/venue_and_event.html', {
            'showEvents': showEvents,
        })
    else:
        messages.success(request, ("No Events available..."))
        return HttpResponseRedirect('event/admin_dashboard')


# MY EVENTS
def my_events(request):
    if request.user.is_authenticated:
        me = request.user.id
        events = Event.objects.filter(attendees=me).order_by('event_date')
        return render(request, 'event/my_events.html', {
            'my_eventsEvents': events,
        })
    else:
        messages.success(request, ("You are not authorized view this page..."))
        return HttpResponseRedirect('/')
# GENERATE A TEXT FILE


def venue_text(request):
    textResonse = HttpResponse(content_type='text/plain')
    textResonse['Content-Disposition'] = 'attachment; filename=venues.txt'

    # Designate The Venue Model
    venueTextOutput = Venue.objects.all()

    # Create blank list
    lines = []
    # Loop Through and Output
    for venue in venueTextOutput:
        # adding DB columns to the text file
        lines.append(
            f'{venue.venue_name}\n{venue.veune_address}\n{venue.veune_zip_code}\n{venue.veune_phone}\n{venue.veune_web}\n{venue.veune_email_address}\n\n\n\n')

    # lines = ["This is line 1\n",
    #          "This is line 2\n",
    #          "This is line 3\n",
    #          "This is line 4\n\n",

    #          "Jonas is Awesome\n\n",
    #          ]

    # Write to TextFile
    textResonse.writelines(lines)
    return textResonse

# GENERATE A CSV / EXCEL FILE


def venue_csv(request):
    textResonse = HttpResponse(content_type='text/csv')
    textResonse['Content-Disposition'] = 'attachment; filename=venues.csv'

    # Creating a csv writer
    csvWriter = csv.writer(textResonse)

    # Designate The Venue Model
    venueTextOutput = Venue.objects.all()

    # add columns to csv file
    csvWriter.writerow(['Venue Name', 'Address', 'Zip Code',
                       'Phone Numbers', 'Website', 'Email'])

    # Loop Through and Output
    for venue in venueTextOutput:
        # adding DB columns to the csv filegit
        csvWriter.writerow(
            [venue.venue_name, venue.veune_address, venue.veune_zip_code, venue.veune_phone, venue.veune_web, venue.veune_email_address])

    return textResonse

# GENERATE A TEXT FILE
# befor you begin, install reportLab in the terminal (pip install)


def venue_pdf(request):
    # Create Bytestream buffer
    buf = io.BytesIO()
    # Create a canvas
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # Create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont('Helvetica', 14)

    #  Add some lines of text
    # lines = [
    #     "This is line 1",
    #     "This is line 2",
    #     "This is line 3",
    #     "This is line 4",
    # ]

    # Designate the VENUE Model
    venueToPdf = Venue.objects.all()

    # Create blank list
    line = []

    for venue in venueToPdf:
        line.append(venue.venue_name)
        line.append(venue.veune_address)
        line.append(venue.veune_zip_code)
        line.append(venue.veune_phone)
        line.append(venue.veune_web)
        line.append(venue.veune_email_address)
        line.append("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

    # Loop
    for line in line:
        textob.textLine(line)

    # Finish up
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    # Return something
    return FileResponse(buf, as_attachment=True, filename='venue.pdf')

# ADD SEARCH VENUE BUTTON ON PAGE


def search_venues(request):
    if request.method == "POST":
        # receiving word from the search input
        searchedWord = request.POST['searched']
        # make search by venue_name in the model
        SearchVenue = Venue.objects.filter(venue_name__contains=searchedWord)

        return render(request, 'venue/search_venues.html', {
            'searchedWord': searchedWord,
            'SearchVenue': SearchVenue
        })
    else:
        return render(request, 'venue/search_venues.html', {})

# ADD SEARCH EVENTS ON PAGE


def search_events(request):
    if request.method == "POST":
        # receiving word from the search input
        searchedWord = request.POST['searched']
        # make search by venue_name in the model
        SearchEvent = Event.objects.filter(event_name__contains=searchedWord)

        return render(request, 'event/search_events.html', {
            'searchedWord': searchedWord,
            'SearchEvent': SearchEvent
        })
    else:
        return render(request, 'event/search_events.html', {})


# EVENTS SECTION VIEW
# Selecting from the Event TABLE IN DATABASE

# ADDING EVENTS INTO THE DB
def add_events(request):
    submitted = False
    if request.method == "POST":
        # if request.user.id == 4:
        if request.user.is_superuser:
            addEventForm = EventFormAdmin(request.POST)

            # form validation
            if addEventForm.is_valid():
                addEventForm.save()
                return HttpResponseRedirect('/addevents')
        else:
            addEventForm = EventFormUsers(request.POST)

            # form validation
            if addEventForm.is_valid():
                # addEventForm.save()

                event = addEventForm.save(commit=False)
                event.event_organizer = request.user  # linking to logged-in-user "request.user"
                event.save()
                return HttpResponseRedirect('/addevents')
    else:
        # just load the page when visited
        if request.user.is_superuser:
            addEventForm = EventFormAdmin
        else:
            addEventForm = EventFormUsers

        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'event/add_events.html', {
        'submitted': submitted,
        'addEventForm': addEventForm,
    })

# LISTING ALL EVENTS


def all_events(request):

    # selecting all columns from the Event tables
    # use '?' in .order_by to make list random when page loads
    events_list = Event.objects.all().order_by('event_date')

    return render(request, 'event/event_lists.html', {
        'eventsList': events_list
    })

# UPDATE / EDIT EVENTS

dbStuff/events/templates/event/add_events.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <center>
            <h1>Add Events</h1>
            <hr>
            <br>
        </center>

        {% if submitted %}
            Your Event has been Submitted Successfully!!!
        {% else %}
            <!-- Add forms -->
            <form action="" method="POST">
                {% csrf_token %}
                
                <!-- add form to page -->
                {{ addEventForm.as_p }}

                <div align="right">
                    <input class="btn btn-outline-success" type="submit" value="Submit"/>
                </div>

            </form>
        {% endif %}
     
    {% else %}
        <div class="alert alert-danger d-flex alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <strong>
                <p>Sorry You have to Log in first...</p>                
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <a href="{% url 'members:login-Page' %}">Login Here</a>
    {% endif %}
    
    


{% endblock %}

dbStuff/events/templates/event/admin_approval.html
{% extends 'base.html' %}

{% block content %}
    
    <center>
        <h1>Admin Dashboard</h1>
        <br>
    </center>

    <!-- Total count output -->
    <div class="card">
        <div class="card-header">
          Total count of Categories
        </div>
        <div class="card-body">
          <p class="card-text">Total Events: {{ totalEvents }}</p>
          <p class="card-text">Total Venue: {{ totalVenue }}</p>
          <p class="card-text">Total Users: {{ totalUsers }}</p>
        </div>
    </div>
    <br>

    <!-- All venue and their Events -->
    <table class="table table-striped table-hover table-bordered">
        <thead align="center">
                <tr>
                    <th>Venue Name</th>
                    <th>Events</th>
                </tr>
        </thead>
        <tbody>
            {% for venue in vennueWithEvent %}
                <tr>
                    <td>
                        <a href="{% url 'events:show-venue' venue.id %}"> {{ venue }}</a>
                    </td>
                    <td>
                        <a href="{% url 'events:venue-event' venue.id %}"> List of Events</a>
                    </td> 
                </tr>
            {% endfor %}
        </tbody>
    </table>


    <!-- Approvals forms -->
    <form action="" method="POST">
        {% csrf_token %}
        <br>
        <h3>Admin Approvals</h3>
        <br>

        <table class="table table-striped table-hover table-bordered">
            <thead align="center">
                    <tr>
                        <th>Event Name</th>
                        <th>Approved</th>
                    </tr>
            </thead>
            <tbody>
                {% for event in allEventToApprove %}
                    <tr>
                        <td>{{ event }}</td>
                        <td>
                            {% if event.approveEvent %}
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" checked="checked" value={{event.id}} name="approvedCheckboxes">
                                </div>
                            {% else %}
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value={{event.id}} name="approvedCheckboxes">
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>

        <input class="btn btn-outline-success btn-sm" type="submit" value="Update"> 
    </form>















{% endblock %}

dbStuff/events/templates/event/event_lists.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>All Events</h1>
    
    {% for event in eventsList %}
        {% if event.approveEvent %}
            <div class="container">
                <div class="card">
                    <div class="card-header">
                        <strong class="text-uppercase">{{ event }}</strong>
                    </div>
        
                    <div class="card-body">
                        <h5 class="card-title">Venue: {{ event.event_venue }} </h5>
                        <p class="card-text">
                            <ul>
                                <li>Date: {{ event.event_date }} </li>
                                <li>Date Till: {{ event.Days_till }}</li>
                                <li>Occured: {{ event.Is_Past }}</li>
                                <li>Venue URL: {{ event.event_venue.veune_web }} </li>
                                <li>Organizer: {{ event.event_organizer }} </li>
                                <li>Description: {{ event.event_description }} </li>
                                <li><b>Attendees:</b> <br>
                                    {% for USER in event.attendees.all  %}
                                        {{ USER }} <br>
                                    {% endfor %}
                                </li>
                                <li>Approved: {{ event.approveEvent }} </li>
                            </ul>
                        </p> 
                    </div>

                    <!-- authenticate -->
                    {% if user.is_authenticated %}
                        {% if user == event.event_organizer %}
                            <div class="card-footer text-muted">
                                <div align="right">
                                    <a href="{% url 'events:update-event' event.id %}" class="btn btn-outline-success btn-sm">Edit</a>
                                    <a href="{% url 'events:delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <br>
        
    {% endfor %}
    















{% endblock %}

dbStuff/events/templates/event/my_events.html
{% extends 'base.html' %}

{% block content %}
    <center>
        <h2>My Events</h2>
        <hr>
        <br><br>
    </center>
        
    {% for event in my_eventsEvents %}
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <strong class="text-uppercase">{{ event }}</strong>
                </div>
    
                <div class="card-body">
                    <h5 class="card-title">Venue: {{ event.event_venue }} </h5>
                    <p class="card-text">
                        <ul>
                            <li>Date: {{ event.event_date }} </li>
                            <li>Venue URL: {{ event.event_venue.veune_web }} </li>
                            <li>Organizer: {{ event.event_organizer }} </li>
                            <li>Description: {{ event.event_description }} </li>
                            <li><b>Attendees:</b> <br>
                                {% for USER in event.attendees.all  %}
                                    {{ USER }} <br>
                                {% endfor %}
                            </li>
                        </ul>
                    </p> 
                </div>

                <!-- authenticate -->
                {% if user.is_authenticated %}
                    {% if user == event.event_organizer %}
                        <div class="card-footer text-muted">
                            <div align="right">
                                <a href="{% url 'events:update-event' event.id %}" class="btn btn-outline-success btn-sm">Edit</a>
                                <a href="{% url 'events:delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <br>
    {% endfor %}

    

{% endblock %}

dbStuff/events/templates/event/search_events.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <strong class="text-uppercase">
                    {% if searchedWord %}
                        You searched for {{ searchedWord }}
                    {% else %}
                        Hey! You forgot to Enter a word to search for a Venue...
                    {% endif %}
                </strong>
            </div>

            <div class="card-body">
                <h5 class="card-title">  </h5>
                <p class="card-text">                            
                    <form method="POST" action="{% url 'events:search-events' %}">
                        {% csrf_token %}

                        <input class="form-control me-2" type="search" placeholder="Search venue" aria-label="Search" name="searched">
                        <br>
                        <button class="btn btn-outline-success btn-sm" type="submit">Search</button>

                    </form>
                </p> 
            </div>                    
        </div>
    </div>
    <br>

    <!-- searched output -->
    

        <!-- searched record output -->
        
        {% for SearchEvent in SearchEvent %}
            <div class="container">
                <div class="card">
                    <div class="card-header">
                        <strong class="text-uppercase">{{ SearchEvent.event_name }}</strong>
                    </div>
        
                    <div class="card-body">
                        <h5 class="card-title">Venue: {{ event.event_venue }} </h5>
                        <p class="card-text">
                            <ul>
                                <li>Date: {{ event.event_date }} </li>
                                <li>Venue URL: {{ event.event_venue.veune_web }} </li>
                                <li>Organizer: {{ event.event_organizer }} </li>
                                <li>Description: {{ event.event_description }} </li>
                                <li><b>Attendees:</b> <br>
                                    {% for USER in event.attendees.all  %}
                                        {{ USER }} <br>
                                    {% endfor %}
                                </li>
                            </ul>
                        </p> 
                    </div>

                    <!-- authenticate -->
                    {% if user.is_authenticated %}
                        {% if user == event.event_organizer %}
                            <div class="card-footer text-muted">
                                <div align="right">
                                    <a href="{% url 'events:update-event' event.id %}" class="btn btn-outline-success btn-sm">Edit</a>
                                    <a href="{% url 'events:delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}           

    

{% endblock %}

dbStuff/events/templates/event/update_event.html
{% extends 'base.html' %}

{% block content %}
    
    {% if user.is_authenticated %}
        {% if user == eventToUpdate.event_organizer %}

            <h1>Edit Event...</h1>
            <br>
            Logged In User: {{ user }}
            <br><br>
            Event Manager: {{ eventToUpdate.event_organizer }}
            <br><br>    
            <form action="" method="POST">
                {% csrf_token%}
                
                <!-- display forms -->
                {{ eventFormToUpdate.as_p }}

                <!-- update button -->
                <div align="right">
                    <input type="submit" value="Update" class="btn btn-success">
                </div>
            </form>

        {% else %}
            <h2>Access Denied</h2>
            
            <div class="alert alert-danger d-flex alert-dismissible fade show" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <strong>
                    <p>Only the Event's manager can update this event...</p>               
                </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            <br>
            Logged In User: {{ user }} <br>
            Event Manager: {{ eventToUpdate.event_organizer }}
        {% endif %}

    {% else %}
        <div class="alert alert-danger d-flex alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <strong>
                <p>Sorry You have to Log in first...</p>                
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <a href="{% url 'members:login-Page' %}">Login Here</a>
    {% endif %}

{% endblock %}